version: '2'
services:
  db:
    image: postgres:9.5
  diversity_in_tech:
    build: .
    command: mix phx.server
    volumes:
      - .:/diversity-in-tech
    ports:
      - "4000:4000"
    depends_on:
      - db
